/** قشرة التطبيق: الخلفية والتنقّل وشريط القرار ولوح المساعد */
export { Background } from './Background'
export { Avatar } from './Avatar'
export { MobileTop } from './MobileTop'
export { Rail, type RailProps } from './Rail'
export { AccountMenu } from './AccountMenu'
export type { ThemeChoice } from '@/lib/theme'
export { DecisionBar, type DecisionBarProps } from './DecisionBar'
export { BulkBar, type BulkBarProps } from './BulkBar'
export { AskDock, type AskDockProps } from './AskDock'
export { AssistantPanel, type AssistantPanelProps } from './AssistantPanel'
