/* The backend's contract, read from the frontend · batch 8.
   Every store writes through one ordered list of operations (`type Op = …` in each store); each
   operation is what becomes a POST on the server. This reads those unions and the stores' storage
   keys and settings keys, and writes docs/API_CONTRACT.md · run again after a store changes:
     node tools/apicontract.mjs */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'

const walk = (d) => readdirSync(d).flatMap((f) => { const p = join(d, f); return statSync(p).isDirectory() ? walk(p) : [p] })
const files = walk('src/data').filter((f) => f.endsWith('.ts'))

const out = ['# API contract · generated from the frontend stores', '', 'Generated by `node tools/apicontract.mjs`. Each store keeps an ordered list of operations in the browser (`localStorage`) and replays it on load; on the server each operation is one `POST`, and the replayed state is what the `GET` returns.', '']
let opsTotal = 0
for (const f of files.sort()) {
  const src = readFileSync(f, 'utf8')
  const m = src.match(/type Op = ([\s\S]*?)\n\)\n|type Op =([\s\S]*?)\n\n/)
  if (!m) continue
  const body = m[1] ?? m[2] ?? ''
  const key = (src.match(/const KEY = '([^']+)'/) ?? [])[1] ?? '—'
  const resource = f.replace('src/data/', '').replace(/\/(store|flow)\.ts$|\.ts$/, '').replace(/\//g, '-')
  const ops = [...body.matchAll(/\{ op: '([a-zA-Z]+)';?([^}]*(?:\{[^}]*\}[^}]*)*)\}/g)].map((x) => ({ op: x[1], fields: x[2].replace(/\s+/g, ' ').trim().replace(/;$/, '') }))
  if (!ops.length) continue
  opsTotal += ops.length
  out.push(`## ${resource}`, '', `- Source: \`${f}\``, `- Browser key: \`${key}\``, `- Read: \`GET /api/${resource}\``, '', '| Operation | Endpoint | Fields |', '|---|---|---|')
  for (const o of ops) out.push(`| \`${o.op}\` | \`POST /api/${resource}/${o.op}\` | ${o.fields.replace(/\|/g, '\\|') || '—'} |`)
  out.push('')
}
const cfg = readFileSync('src/lib/config.ts', 'utf8')
const keys = [...cfg.matchAll(/^\s+(\w+): '(ab-cfg-[^']+)'/gm)]
const extra = [['ai', 'ab-cfg-ai'], ['auth', 'ab-cfg-auth'], ['demo', 'ab-cfg-demo']]
out.push('## Settings', '', 'Each settings group is one document: `GET /api/settings/{name}` and `PUT /api/settings/{name}`. Every save is also appended to the settings log (`ab-settings-log` · `GET /api/settings/log`).', '', '| Name | Browser key |', '|---|---|')
for (const [, n, k] of keys) out.push(`| ${n} | \`${k}\` |`)
for (const [n, k] of extra) out.push(`| ${n} | \`${k}\` |`)
out.push('', '## External services', '', '| Service | Contract | Setting |', '|---|---|---|',
  '| AI readings | `POST {endpoint}/{task}` JSON → `{ text, items? }` · tasks: summary, report, spell, document, clauses, impact | settings › الذكاء الاصطناعي |',
  '| Document reading | `POST {endpoint}/document` multipart `file`, `kind` → `{ fields: [{ key, label, value }] }` | same |',
  '| Email and SMS | the outbox messages with their final text, handed to `{endpoint}` · delivery state reported back | settings › الإشعارات › القوالب والبوابة |',
  '| E-signature | today: a code on the signer\'s phone and the SHA-256 of the signed text · a provider replaces `via: otp` with its certificate | agreements |',
  '| Ehsan platform | the operations export (CSV/XLSX) today · the platform API returns the same rows | partners › مطابقة إحسان |',
  '| Sign-in | passwords, tokens and lockout on the server · the screens already enforce tries, lock, idle timeout and sign-out everywhere | permissions › حماية الدخول |',
  '')
writeFileSync('docs/API_CONTRACT.md', out.join('\n'))
console.log(`docs/API_CONTRACT.md · ${opsTotal} operations · ${keys.length + extra.length} settings`)
